-- Könyvesbolt adatainak feltöltése
--
INSERT INTO store (name, description, tax_id, address, phone, email, url) VALUES
('Bookshop', 'A bookstore with a wide selection of classic and contemporary literature.', '123456789', '123 Main St, New York, USA', 1234567890, 'email@example.com', 'http://www.example.com');

-- Könyvek adatainak feltöltése
--
INSERT INTO book (title, author, description, price, stock) VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 'A novel set in the Jazz Age that tells the story of Jay Gatsby and his unrequited love for Daisy Buchanan.', 10, 0),
('To Kill a Mockingbird', 'Harper Lee', 'A novel about the serious issues of rape and racial inequality, told through the eyes of a young girl.', 12, 0),
('1984', 'George Orwell', 'A dystopian novel set in a totalitarian society under constant surveillance.', 15, 30),
('Pride and Prejudice', 'Jane Austen', 'A romantic novel that also critiques the British landed gentry at the end of the 18th century.', 8, 20),
('The Catcher in the Rye', 'J.D. Salinger', 'A novel about the experiences of a young man in New York City after being expelled from prep school.', 10, 25),
('The Hobbit', 'J.R.R. Tolkien', 'A fantasy novel about the adventures of Bilbo Baggins, a hobbit who sets out on a quest to win a share of the treasure guarded by Smaug the dragon.', 14, 35),
('Fahrenheit 451', 'Ray Bradbury', 'A dystopian novel about a future society where books are banned and "firemen" burn any that are found.', 13, 45),
('Moby-Dick', 'Herman Melville', 'A novel about the voyage of the whaling ship Pequod and its captain, Ahab, who is obsessed with hunting the giant white whale Moby Dick.', 18, 15),
('War and Peace', 'Leo Tolstoy', 'A novel that chronicles the history of the French invasion of Russia and the impact of the Napoleonic era on Tsarist society.', 20, 10),
('The Odyssey', 'Homer', 'An epic poem that tells the story of Odysseus''s ten-year journey home after the Trojan War.', 16, 22),
('Crime and Punishment', 'Fyodor Dostoevsky', 'A novel about the mental anguish and moral dilemmas of an impoverished ex-student who kills a pawnbroker for her money.', 14, 18),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'A novel about the spiritual and moral struggles of the Karamazov family.', 17, 12),
('Brave New World', 'Aldous Huxley', 'A dystopian novel set in a futuristic World State, where citizens are environmentally engineered into an intelligence-based social hierarchy.', 15, 28),
('Jane Eyre', 'Charlotte Brontë', 'A novel about the experiences of the orphaned title character, including her growth to adulthood and her love for Mr. Rochester.', 12, 32),
('Wuthering Heights', 'Emily Brontë', 'A novel about the intense and almost demonic love between Catherine Earnshaw and Heathcliff, a foundling adopted by Catherine''s father.', 11, 27),
('The Divine Comedy', 'Dante Alighieri', 'An epic poem that describes Dante''s journey through Hell, Purgatory, and Paradise.', 19, 14),
('The Iliad', 'Homer', 'An epic poem that tells the story of the last year of the Trojan War.', 16, 20),
('Les Misérables', 'Victor Hugo', 'A novel that examines the nature of law and grace, and expounds upon the history of France, the architecture of Paris, politics, moral philosophy, and justice.', 18, 16),
('Anna Karenina', 'Leo Tolstoy', 'A novel about the tragic love affair between the title character and the dashing officer Count Vronsky.', 17, 19),
('Madame Bovary', 'Gustave Flaubert', 'A novel about the life of a doctor''s wife who has adulterous affairs and lives beyond her means in order to escape the banalities and emptiness of provincial life.', 14, 21),
('The Count of Monte Cristo', 'Alexandre Dumas', 'A novel about a man who is wrongfully imprisoned, escapes from jail, acquires a fortune, and sets about exacting revenge on those responsible for his imprisonment.', 20, 13),
('The Picture of Dorian Gray', 'Oscar Wilde', 'A novel about a young man whose portrait ages while he remains youthful and beautiful.', 12, 24),
('Dracula', 'Bram Stoker', 'A novel about the vampire Count Dracula''s attempt to move from Transylvania to England so that he may find new blood and spread the undead curse.', 15, 26),
('Frankenstein', 'Mary Shelley', 'A novel about a young scientist who creates a grotesque creature in an unorthodox scientific experiment.', 13, 29),
('The Adventures of Huckleberry Finn', 'Mark Twain', 'A novel about a young boy who runs away from home and floats down the Mississippi River on a raft with a runaway slave.', 11, 33),
('The Adventures of Tom Sawyer', 'Mark Twain', 'A novel about a young boy growing up along the Mississippi River.', 10, 31),
('The Scarlet Letter', 'Nathaniel Hawthorne', 'A novel about a woman who is shunned by her Puritan community after she gives birth to an illegitimate child.', 12, 23),
('Great Expectations', 'Charles Dickens', 'A novel about the growth and personal development of an orphan named Pip.', 14, 25),
('David Copperfield', 'Charles Dickens', 'A novel about the life of the title character, from his childhood to his maturity.', 15, 22),
('A Tale of Two Cities', 'Charles Dickens', 'A novel set in London and Paris before and during the French Revolution.', 13, 28),
('Oliver Twist', 'Charles Dickens', 'A novel about an orphan who runs away from a workhouse and meets a group of juvenile criminals.', 11, 30),
('Bleak House', 'Charles Dickens', 'A novel that satirizes the English legal system.', 16, 17),
('The Old Man and the Sea', 'Ernest Hemingway', 'A novel about an aging fisherman who struggles with a giant marlin far out in the Gulf Stream.', 10, 34),
('For Whom the Bell Tolls', 'Ernest Hemingway', 'A novel about an American dynamiter who fights in the Spanish Civil War.', 14, 20),
('The Sun Also Rises', 'Ernest Hemingway', 'A novel about a group of American and British expatriates who travel from Paris to Pamplona to watch the running of the bulls and the bullfights.', 12, 27),
('A Farewell to Arms', 'Ernest Hemingway', 'A novel about a love affair between an American ambulance driver in the Italian army and a British nurse during World War I.', 13, 26),
('The Grapes of Wrath', 'John Steinbeck', 'A novel about the Joad family, who are driven from their Oklahoma home by drought, economic hardship, and changes in the agriculture industry.', 15, 19),
('Of Mice and Men', 'John Steinbeck', 'A novel about two displaced migrant ranch workers who move from place to place in California in search of new job opportunities during the Great Depression.', 10, 32),
('East of Eden', 'John Steinbeck', 'A novel that retells the story of Cain and Abel in the context of two families in California''s Salinas Valley.', 18, 14),
('The Pearl', 'John Steinbeck', 'A novel about a poor pearl diver who finds a giant pearl that he believes will bring his family fortune.', 11, 29),
('The Red Badge of Courage', 'Stephen Crane', 'A novel about a young soldier in the American Civil War who flees from the field of battle.', 12, 24),
('The Call of the Wild', 'Jack London', 'A novel about a domesticated dog who returns to the wild.', 13, 28),
('White Fang', 'Jack London', 'A novel about a wild wolfdog''s journey to domestication.', 14, 22),
('The Sea-Wolf', 'Jack London', 'A novel about a literary critic who is swept to sea and becomes the captive of a brutal sea captain.', 15, 18),
('Treasure Island', 'Robert Louis Stevenson', 'A novel about a young boy who finds a treasure map and sets off on a dangerous adventure to find the treasure.', 10, 33),
('Kidnapped', 'Robert Louis Stevenson', 'A novel about a young boy who is kidnapped and sold into slavery.', 11, 30),
('Strange Case of Dr Jekyll and Mr Hyde', 'Robert Louis Stevenson', 'A novel about a lawyer who investigates the strange occurrences between his old friend Dr. Henry Jekyll and the evil Edward Hyde.', 12, 25),
('The Time Machine', 'H.G. Wells', 'A novel about an inventor who travels through time and witnesses the future of humanity.', 13, 27),
('The War of the Worlds', 'H.G. Wells', 'A novel about an alien invasion of Earth.', 14, 23),
('The Invisible Man', 'H.G. Wells', 'A novel about a scientist who discovers how to make himself invisible.', 15, 21),
('The Island of Doctor Moreau', 'H.G. Wells', 'A novel about a shipwrecked man who ends up on an island where a mad scientist is creating human-animal hybrids.', 16, 19),
('Egri csillagok', 'Géza Gárdonyi', 'A historical novel set during the 16th century, focusing on the Siege of Eger. It tells the story of the Hungarian defenders against the Ottoman Empire.', 15, 50),
('A Pál utcai fiúk', 'Ferenc Molnár', 'A novel about a group of boys from Budapest who defend their playground from another gang. It is a story of friendship, loyalty, and bravery.', 12, 40),
('Az arany ember', 'Mór Jókai', 'A novel about a man who discovers a hidden treasure and the moral dilemmas that follow. It explores themes of love, betrayal, and redemption.', 14, 35),
('Az ember tragédiája', 'Imre Madách', 'A dramatic poem that explores the history of mankind through a series of dream sequences. It reflects on human nature and destiny.', 18, 25),
('Az ajtó', 'Magda Szabó', 'A novel about the complex relationship between a writer and her housekeeper. It explores themes of trust, betrayal, and the human condition.', 16, 30),
('Sorstalanság', 'Imre Kertész', 'A semi-autobiographical novel about a young Hungarian boy''s experiences in Auschwitz. It is a poignant exploration of identity and survival.', 20, 20),
('Utas és holdvilág', 'Antal Szerb', 'A novel about a man who abandons his conventional life to search for meaning. It is a blend of romance, adventure, and existential reflection.', 15, 28),
('A Pendragon legenda', 'Antal Szerb', 'A mystery novel set in Wales, combining elements of gothic fiction and humor. It follows a Hungarian scholar who gets entangled in a family curse.', 13, 32),
('Szindbád', 'Gyula Krúdy', 'A collection of short stories about the romantic and melancholic adventures of Szindbád. It captures the essence of early 20th-century Hungary.', 14, 27),
('A fehér király', 'György Dragomán', 'A novel about a young boy growing up in a totalitarian regime. It is a powerful depiction of childhood and resilience.', 17, 22),
('Sátántangó', 'László Krasznahorkai', 'A novel about the collapse of a small Hungarian village. It is known for its intricate structure and bleak atmosphere.', 19, 18),
('Háború és háború', 'László Krasznahorkai', 'A novel about a man who discovers a mysterious manuscript and becomes obsessed with it. It explores themes of history, memory, and madness.', 18, 20),
('Az ellenállás melankóliája', 'László Krasznahorkai', 'A novel about a small town that is disrupted by the arrival of a mysterious circus. It is a dark and surreal exploration of power and chaos.', 16, 24),
('Apák könyve', 'Miklós Vámos', 'A multi-generational saga that follows a Hungarian family through centuries. It is a rich tapestry of history, culture, and personal stories.', 20, 15),
('Harmonia caelestis', 'Péter Esterházy', 'A novel that intertwines the history of Hungary with the author''s own family history. It is a complex and lyrical exploration of identity.', 22, 12),
('A kilencedik', 'Ferenc Barnás', 'A novel about a young boy growing up in a large, dysfunctional family. It is a raw and intimate portrayal of childhood and family dynamics.', 14, 26),
('A tanú', 'Ágnes Heller', 'A philosophical novel that explores the nature of memory and testimony. It is a profound meditation on history and truth.', 18, 19),
('Egy családregény vége', 'Péter Nádas', 'A novel about a young boy growing up in post-war Hungary. It is a poignant exploration of memory, identity, and family.', 16, 23),
('Párhuzamos történetek', 'Péter Nádas', 'A monumental novel that weaves together multiple narratives spanning the 20th century. It is a complex and ambitious exploration of history and human experience.', 25, 10),
('Emlékiratok könyve', 'Péter Nádas', 'A novel that intertwines the lives of three characters in different time periods. It is a rich and intricate exploration of memory and identity.', 22, 14),
('A gyertyák csonkig égnek', 'Sándor Márai', 'A novel about two old friends who reunite after many years. It explores themes of friendship, betrayal, and the passage of time.', 15, 30),
('Eszter hagyatéka', 'Sándor Márai', 'A novel about a woman who reflects on her past and the choices she made. It is a poignant exploration of love and regret.', 14, 25);

-- Vásárlók adatainak feltöltése
--
INSERT INTO customer (email, first_name, last_name, country, city, address, phone) VALUES
('john.doe@example.com', 'John', 'Doe', 'USA', 'New York', '123 Main St', '123-456-7890'),
('jane.smith@example.com', 'Jane', 'Smith', 'USA', 'Los Angeles', '456 Elm St', '234-567-8901'),
('alice.jones@example.com', 'Alice', 'Jones', 'USA', 'Chicago', '789 Oak St', '345-678-9012'),
('bob.brown@example.com', 'Bob', 'Brown', 'USA', 'Houston', '101 Pine St', '456-789-0123'),
('carol.white@example.com', 'Carol', 'White', 'USA', 'Phoenix', '202 Maple St', '567-890-1234'),
('dave.green@example.com', 'Dave', 'Green', 'USA', 'Philadelphia', '303 Cedar St', '678-901-2345'),
('eve.black@example.com', 'Eve', 'Black', 'USA', 'San Antonio', '404 Birch St', '789-012-3456'),
('frank.gray@example.com', 'Frank', 'Gray', 'USA', 'San Diego', '505 Walnut St', '890-123-4567'),
('grace.hall@example.com', 'Grace', 'Hall', 'USA', 'Dallas', '606 Chestnut St', '901-234-5678'),
('henry.king@example.com', 'Henry', 'King', 'USA', 'San Jose', '707 Spruce St', '012-345-6789'),
('irene.lee@example.com', 'Irene', 'Lee', 'USA', 'Austin', '808 Redwood St', '123-456-7891'),
('jack.martin@example.com', 'Jack', 'Martin', 'USA', 'Jacksonville', '909 Cypress St', '234-567-8902'),
('karen.moore@example.com', 'Karen', 'Moore', 'USA', 'Fort Worth', '1010 Palm St', '345-678-9013'),
('larry.scott@example.com', 'Larry', 'Scott', 'USA', 'Columbus', '1111 Fir St', '456-789-0124'),
('mary.adams@example.com', 'Mary', 'Adams', 'USA', 'Charlotte', '1212 Willow St', '567-890-1235'),
('nancy.baker@example.com', 'Nancy', 'Baker', 'USA', 'San Francisco', '1313 Poplar St', '678-901-2346'),
('oscar.clark@example.com', 'Oscar', 'Clark', 'USA', 'Indianapolis', '1414 Ash St', '789-012-3457'),
('paul.davis@example.com', 'Paul', 'Davis', 'USA', 'Seattle', '1515 Beech St', '890-123-4568'),
('quincy.evans@example.com', 'Quincy', 'Evans', 'USA', 'Denver', '1616 Hickory St', '901-234-5679'),
('rachel.foster@example.com', 'Rachel', 'Foster', 'USA', 'Washington', '1717 Magnolia St', '012-345-6790'),
('steve.garcia@example.com', 'Steve', 'Garcia', 'USA', 'Boston', '1818 Dogwood St', '123-456-7892'),
('tina.harris@example.com', 'Tina', 'Harris', 'USA', 'El Paso', '1919 Sycamore St', '234-567-8903'),
('ursula.hernandez@example.com', 'Ursula', 'Hernandez', 'USA', 'Detroit', '2020 Alder St', '345-678-9014'),
('victor.jackson@example.com', 'Victor', 'Jackson', 'USA', 'Nashville', '2121 Sequoia St', '456-789-0125'),
('wendy.johnson@example.com', 'Wendy', 'Johnson', 'USA', 'Memphis', '2222 Redwood St', '567-890-1236'),
('xander.kelly@example.com', 'Xander', 'Kelly', 'USA', 'Portland', '2323 Cedar St', '678-901-2347'),
('yvonne.lewis@example.com', 'Yvonne', 'Lewis', 'USA', 'Oklahoma City', '2424 Birch St', '789-012-3458'),
('zach.miller@example.com', 'Zach', 'Miller', 'USA', 'Las Vegas', '2525 Walnut St', '890-123-4569'),
('amy.nelson@example.com', 'Amy', 'Nelson', 'USA', 'Louisville', '2626 Chestnut St', '901-234-5670'),
('brian.owens@example.com', 'Brian', 'Owens', 'USA', 'Baltimore', '2727 Spruce St', '012-345-6791'),
('cathy.parker@example.com', 'Cathy', 'Parker', 'USA', 'Milwaukee', '2828 Redwood St', '123-456-7893'),
('dan.quinn@example.com', 'Dan', 'Quinn', 'USA', 'Albuquerque', '2929 Cypress St', '234-567-8904'),
('ellen.roberts@example.com', 'Ellen', 'Roberts', 'USA', 'Tucson', '3030 Palm St', '345-678-9015'),
('fred.sanders@example.com', 'Fred', 'Sanders', 'USA', 'Fresno', '3131 Fir St', '456-789-0126'),
('gina.taylor@example.com', 'Gina', 'Taylor', 'USA', 'Sacramento', '3232 Willow St', '567-890-1237'),
('harry.thomas@example.com', 'Harry', 'Thomas', 'USA', 'Kansas City', '3333 Poplar St', '678-901-2348'),
('isabel.turner@example.com', 'Isabel', 'Turner', 'USA', 'Long Beach', '3434 Ash St', '789-012-3459'),
('jason.walker@example.com', 'Jason', 'Walker', 'USA', 'Mesa', '3535 Beech St', '890-123-4570'),
('katie.wilson@example.com', 'Katie', 'Wilson', 'USA', 'Atlanta', '3636 Hickory St', '901-234-5671'),
('leo.young@example.com', 'Leo', 'Young', 'USA', 'Colorado Springs', '3737 Magnolia St', '012-345-6792'),
('mona.zimmerman@example.com', 'Mona', 'Zimmerman', 'USA', 'Raleigh', '3838 Dogwood St', '123-456-7894'),
('nick.anderson@example.com', 'Nick', 'Anderson', 'USA', 'Miami', '3939 Sycamore St', '234-567-8905'),
('olivia.bell@example.com', 'Olivia', 'Bell', 'USA', 'Virginia Beach', '4040 Alder St', '345-678-9016'),
('peter.carter@example.com', 'Peter', 'Carter', 'USA', 'Omaha', '4141 Sequoia St', '456-789-0127'),
('quinn.daniels@example.com', 'Quinn', 'Daniels', 'USA', 'Oakland', '4242 Redwood St', '567-890-1238'),
('ruth.edwards@example.com', 'Ruth', 'Edwards', 'USA', 'Minneapolis', '4343 Cedar St', '678-901-2349'),
('sam.fisher@example.com', 'Sam', 'Fisher', 'USA', 'Tulsa', '4444 Birch St', '789-012-3460'),
('tina.gonzalez@example.com', 'Tina', 'Gonzalez', 'USA', 'Arlington', '4545 Walnut St', '890-123-4571'),
('ulysses.hall@example.com', 'Ulysses', 'Hall', 'USA', 'New Orleans', '4646 Chestnut St', '901-234-5672'),
('victoria.hernandez@example.com', 'Victoria', 'Hernandez', 'USA', 'Wichita', '4747 Spruce St', '012-345-6793'),
('istvan.kovacs@example.hu', 'István', 'Kovács', 'Hungary', 'Budapest', 'Kossuth Lajos utca 1', '+36-1-234-5678'),
('maria.nagy@example.hu', 'Mária', 'Nagy', 'Hungary', 'Debrecen', 'Petőfi Sándor utca 2', '+36-52-234-5678'),
('laszlo.toth@example.hu', 'László', 'Tóth', 'Hungary', 'Szeged', 'Rákóczi Ferenc utca 3', '+36-62-234-5678'),
('erzsebet.kiss@example.hu', 'Erzsébet', 'Kiss', 'Hungary', 'Miskolc', 'Széchenyi István utca 4', '+36-46-234-5678'),
('janos.horvath@example.hu', 'János', 'Horváth', 'Hungary', 'Pécs', 'Deák Ferenc utca 5', '+36-72-234-5678'),
('anna.varga@example.hu', 'Anna', 'Varga', 'Hungary', 'Győr', 'Kossuth Lajos utca 6', '+36-96-234-5678'),
('zoltan.szabo@example.hu', 'Zoltán', 'Szabó', 'Hungary', 'Nyíregyháza', 'Petőfi Sándor utca 7', '+36-42-234-5678'),
('klara.farkas@example.hu', 'Klára', 'Farkas', 'Hungary', 'Kecskemét', 'Rákóczi Ferenc utca 8', '+36-76-234-5678'),
('tamas.kovacs@example.hu', 'Tamás', 'Kovács', 'Hungary', 'Székesfehérvár', 'Széchenyi István utca 9', '+36-22-234-5678'),
('eva.nagy@example.hu', 'Éva', 'Nagy', 'Hungary', 'Szombathely', 'Deák Ferenc utca 10', '+36-94-234-5678'),
('gyorgy.toth@example.hu', 'György', 'Tóth', 'Hungary', 'Tatabánya', 'Kossuth Lajos utca 11', '+36-34-234-5678'),
('ildiko.kiss@example.hu', 'Ildikó', 'Kiss', 'Hungary', 'Kaposvár', 'Petőfi Sándor utca 12', '+36-82-234-5678'),
('ferenc.horvath@example.hu', 'Ferenc', 'Horváth', 'Hungary', 'Békéscsaba', 'Rákóczi Ferenc utca 13', '+36-66-234-5678'),
('agnes.varga@example.hu', 'Ágnes', 'Varga', 'Hungary', 'Zalaegerszeg', 'Széchenyi István utca 14', '+36-92-234-5678'),
('peter.szabo@example.hu', 'Péter', 'Szabó', 'Hungary', 'Eger', 'Deák Ferenc utca 15', '+36-36-234-5678'),
('marta.farkas@example.hu', 'Márta', 'Farkas', 'Hungary', 'Sopron', 'Kossuth Lajos utca 16', '+36-99-234-5678'),
('laszlo.kovacs@example.hu', 'László', 'Kovács', 'Hungary', 'Veszprém', 'Petőfi Sándor utca 17', '+36-88-234-5678'),
('zsuzsanna.nagy@example.hu', 'Zsuzsanna', 'Nagy', 'Hungary', 'Szolnok', 'Rákóczi Ferenc utca 18', '+36-56-234-5678'),
('istvan.toth@example.hu', 'István', 'Tóth', 'Hungary', 'Szekszárd', 'Széchenyi István utca 19', '+36-74-234-5678'),
('maria.kiss@example.hu', 'Mária', 'Kiss', 'Hungary', 'Hódmezővásárhely', 'Deák Ferenc utca 20', '+36-62-234-5678');

-- Rendelések adatainak feltöltése
--
INSERT INTO "order" (store_id, customer_id, status, created) VALUES
(1, 1, 'cart', now()),
(1, 2, 'cart', now()),
(1, 3, 'cancelled', now()),
(1, 4, 'cart', now()),
(1, 5, 'processing', now()),
(1, 6, 'shipped', now()),
(1, 7, 'cart', now()),
(1, 8, 'cart', now()),
(1, 9, 'processing', now()),
(1, 10, 'delivered', now()),
(1, 11, 'shipped', now()),
(1, 12, 'delivered', now()),
(1, 13, 'shipped', now()),
(1, 14, 'cart', now()),
(1, 15, 'delivered', now()),
(1, 16, 'returned', now()),
(1, 17, 'delivered', now()),
(1, 18, 'unpaid', now()),
(1, 19, 'delivered', now()),
(1, 20, 'delivered', now()),
(1, 21, 'unpaid', now()),
(1, 22, 'delivered', now()),
(1, 23, 'cart', now()),
(1, 24, 'cart', now()),
(1, 25, 'delivered', now()),
(1, 26, 'delivered', now()),
(1, 27, 'delivered', now()),
(1, 28, 'returned', now()),
(1, 29, 'cart', now()),
(1, 30, 'cart', now()),
(1, 31, 'cart', now()),
(1, 32, 'cancelled', now()),
(1, 33, 'unpaid', now()),
(1, 34, 'unpaid', now()),
(1, 35, 'delivered', now()),
(1, 36, 'delivered', now()),
(1, 37, 'delivered', now()),
(1, 38, 'delivered', now()),
(1, 39, 'cart', now()),
(1, 40, 'cart', now()),
(1, 41, 'cart', now()),
(1, 42, 'processing', now()),
(1, 43, 'delivered', now()),
(1, 44, 'delivered', now()),
(1, 45, 'delivered', now()),
(1, 46, 'unpaid', now()),
(1, 47, 'refunded', now()),
(1, 48, 'delivered', now()),
(1, 49, 'delivered', now()),
(1, 50, 'delivered', now()),
(1, 51, 'unpaid', now()),
(1, 52, 'delivered', now()),
(1, 53, 'delivered', now()),
(1, 54, 'delivered', now()),
(1, 55, 'delivered', now()),
(1, 56, 'delivered', now()),
(1, 57, 'delivered', now()),
(1, 58, 'delivered', now()),
(1, 59, 'delivered', now()),
(1, 60, 'unpaid', now()),
(1, 61, 'delivered', now()),
(1, 62, 'delivered', now()),
(1, 63, 'unpaid', now()),
(1, 64, 'paid', now()),
(1, 65, 'paid', now()),
(1, 66, 'paid', now()),
(1, 67, 'paid', now()),
(1, 68, 'delivered', now()),
(1, 69, 'delivered', now()),
(1, 70, 'delivered', now()),
(1, 71, 'paid', now()),
(1, 72, 'paid', now()),
(1, 73, 'paid', now()),
(1, 74, 'delivered', now()),
(1, 75, 'delivered', now()),
(1, 76, 'delivered', now()),
(1, 77, 'paid', now()),
(1, 78, 'paid', now()),
(1, 79, 'paid', now()),
(1, 80, 'delivered', now()),
(1, 81, 'delivered', now()),
(1, 82, 'delivered', now()),
(1, 83, 'paid', now()),
(1, 84, 'paid', now()),
(1, 85, 'paid', now()),
(1, 86, 'paid', now()),
(1, 87, 'paid', now()),
(1, 88, 'delivered', now()),
(1, 89, 'delivered', now()),
(1, 90, 'delivered', now()),
(1, 91, 'delivered', now()),
(1, 92, 'delivered', now()),
(1, 93, 'paid', now()),
(1, 94, 'paid', now()),
(1, 95, 'paid', now()),
(1, 96, 'delivered', now()),
(1, 97, 'delivered', now()),
(1, 98, 'paid', now()),
(1, 99, 'delivered', now()),
(1, 100, 'paid', now());

-- Rendelés tételek feltöltése
--
INSERT INTO order_item (order_id, book_id, quantity) VALUES
(1, 1, 1),
(1, 2, 1),
(2, 3, 1),
(2, 4, 1),
(3, 5, 1),
(3, 6, 1),
(4, 7, 1),
(4, 8, 1),
(5, 9, 1),
(5, 10, 1),
(6, 11, 1),
(6, 12, 1),
(7, 13, 1),
(7, 14, 1),
(8, 15, 1),
(8, 16, 1),
(9, 17, 1),
(9, 18, 1),
(10, 19, 1),
(10, 20, 1),
(11, 21, 1),
(11, 22, 1),
(12, 23, 1),
(12, 24, 1),
(13, 25, 1),
(13, 26, 1),
(14, 27, 1),
(14, 28, 1),
(15, 29, 1),
(15, 30, 1),
(16, 31, 1),
(16, 32, 1),
(17, 33, 1),
(17, 34, 1),
(18, 35, 1),
(18, 36, 1),
(19, 37, 1),
(19, 38, 1),
(20, 39, 1),
(20, 40, 1),
(21, 41, 1),
(21, 42, 1),
(22, 43, 1),
(22, 44, 1),
(23, 45, 1),
(23, 46, 1),
(24, 47, 1),
(24, 48, 1),
(25, 49, 1),
(25, 50, 1),
(26, 1, 1),
(26, 2, 1),
(27, 3, 1),
(27, 4, 1),
(28, 5, 1),
(28, 6, 1),
(29, 7, 1),
(29, 8, 1),
(30, 9, 1),
(30, 10, 1),
(31, 11, 1),
(31, 12, 1),
(32, 13, 1),
(32, 14, 1),
(33, 15, 1),
(33, 16, 1),
(34, 17, 1),
(34, 18, 1),
(35, 19, 1),
(35, 20, 1),
(36, 21, 1),
(36, 22, 1),
(37, 23, 1),
(37, 24, 1),
(38, 25, 1),
(38, 26, 1),
(39, 27, 1),
(39, 28, 1),
(40, 29, 1),
(40, 30, 1),
(41, 31, 1),
(41, 32, 1),
(42, 33, 1),
(42, 34, 1),
(43, 35, 1),
(43, 36, 1),
(44, 37, 1),
(44, 38, 1),
(45, 39, 1),
(45, 40, 1),
(46, 41, 1),
(46, 42, 1),
(47, 43, 1),
(47, 44, 1),
(48, 45, 1),
(48, 46, 1),
(49, 47, 1),
(49, 48, 1),
(50, 49, 1),
(50, 50, 1),
(51, 1, 1),
(51, 2, 1),
(52, 3, 1),
(52, 4, 1),
(53, 5, 1),
(53, 6, 1),
(54, 7, 1),
(54, 8, 1),
(55, 9, 1),
(55, 10, 1),
(56, 11, 1),
(56, 12, 1),
(57, 13, 1),
(57, 14, 1),
(58, 15, 1),
(58, 16, 1),
(59, 17, 1),
(59, 18, 1),
(60, 19, 1),
(60, 20, 1),
(61, 21, 1),
(61, 22, 1),
(62, 23, 1),
(62, 24, 1),
(63, 25, 1),
(63, 26, 1),
(64, 27, 1),
(64, 28, 1),
(65, 29, 1),
(65, 30, 1),
(66, 31, 1),
(66, 32, 1),
(67, 33, 1),
(67, 34, 1),
(68, 35, 1),
(68, 36, 1),
(69, 37, 1),
(69, 38, 1),
(70, 39, 1),
(70, 40, 1),
(71, 41, 1),
(71, 42, 1),
(72, 43, 1),
(72, 44, 1),
(73, 45, 1),
(73, 46, 1),
(74, 47, 1),
(74, 48, 1),
(75, 49, 1),
(75, 50, 1),
(76, 1, 1),
(76, 2, 1),
(77, 3, 1),
(77, 4, 1),
(78, 5, 1),
(78, 6, 1),
(79, 7, 1),
(79, 8, 1),
(80, 9, 1),
(80, 10, 1),
(81, 11, 1),
(81, 12, 1),
(82, 13, 1),
(82, 14, 1),
(83, 15, 1),
(83, 16, 1),
(84, 17, 1),
(84, 18, 1),
(85, 19, 1),
(85, 20, 1),
(86, 21, 1),
(86, 22, 1),
(87, 23, 1),
(87, 24, 1),
(88, 25, 1),
(88, 26, 1),
(89, 27, 1),
(89, 28, 1),
(90, 29, 1),
(90, 30, 1),
(91, 31, 1),
(91, 32, 1),
(92, 33, 1),
(92, 34, 1),
(93, 35, 1),
(93, 36, 1),
(94, 37, 1),
(94, 38, 1),
(95, 39, 1),
(95, 40, 1),
(96, 41, 1),
(96, 42, 1),
(97, 43, 1),
(97, 44, 1),
(98, 45, 1),
(98, 46, 1),
(99, 47, 1),
(99, 48, 1),
(100, 49, 1),
(100, 50, 1);
